data:
  paths:
    raw_user_data: 'data/raw/tianchi_fresh_comp_train_user_2w.csv'
    raw_item_data: 'data/raw/tianchi_fresh_comp_train_item_2w.csv'
    processed_data_dir: 'data/processed'
    output_dir: 'data/output'
    checkpoint_dir: 'checkpoints'
    log_dir: 'logs'
  features:
    categorical:
      - user_id
      - item_id
      - category
    numerical:
      - behavior_count
      - behavior_type
      - category_count
      - conversion_rate
    sequence:
      max_length: 50
      padding: 'pre'
      truncating: 'pre'
      pad_value: 0
    user:
      categorical:
        - user_id
      numerical:
        - hour
        - day
        - weekday
    item:
      categorical:
        - item_id
        - category
      numerical: []

features:
  time_windows: [1, 3, 7, 14]
  behavuir_types: [1, 2, 3, 4]
  chunk_size: 1000000
  memory_optimize: true
  save_dir: 'data/processed/features'
  user_features:
    enable_behavior_count: true
    enable_category_preference: true
    enable_time_based: true
  item_features:
    enable_behavior_count: true
    enable_user_stats: true
    enable_time_based: true
  processing:
    batch_size: 100000
    n_jobs: -1

device:
  accelerator: 'gpu'
  devices: [0]  # 修改为列表格式
  strategy: 'auto'
  precision: 16

model:
  training:
    batch_size: 8192  # 修复了这里的格式
    num_epochs: 10
    early_stopping:
      patience: 5
      min_delta: 0.001
    optimization:
      accumulate_grad_batches: 1
      gradient_clip_val: 1.0
      precision: 16
      cudnn_benchmark: true

training:
  train_end_date: '2014-12-18'
  pred_date: '2014-12-19'
  validation_days: 1
  top_k: 20
  enable_memory_optimize: true
  gc_collect_interval: 2
  memory_limit_gb: 16
  save_checkpoints: true
  checkpoint_interval: 5

logging:
  level: 'INFO'
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: 'logs/recommender.log'
  enable_memory_logging: true
  memory_log_interval: 1000
  log_feature_info: true

system:
  num_workers: 16
  pin_memory: true
  prefetch_factor: 4
  memory_optimize:
    enable: true
    min_memory_gb: 8
    max_memory_gb: 70
    cleaning_threshold_gb: 65
